### ISSUE TITLE
Basic Errors from Language Server Protocol

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/Planning#12]
Collect errors and return to UI --> communicate to user

**Comment by phated** [comment]
@Savio-Sou is this done? The LSP has compile errors and warnings now.

**Comment by Savio-Sou** [comment]
Thanks for the ping. Let's close it for now.

(Not sure if there were any extra context, it was a draft issue transferred from the old Tooling board; feel free to reopen if need to.)
