### ISSUE TITLE
Epic: Package Registry

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/Planning#15]
**Goal**

A site for Noir package / library discovery and download.

```[tasklist]
- [x] Specs
- [ ] Independent site: Listing --> Searching --> Sorting (e.g. by date, by popularity)
```

Reference:
- Rust's [crates](https://crates.io/)
- JavaScript's [NPM](https://www.npmjs.com/)
- Java's Maven
- Leo's [Aleo Package Manager](https://aleo.pm/)

**Comment by jonybur** [comment]
[redacted]
