### ISSUE TITLE
Nargo builds protected by Tests

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/Planning#8]
As a Vendor of Noir Tools
I need to protect Nargo builds with tests
so that consumers can be confident about it's functions

Acceptance Criteria:
1. Nargo builds successfully through CI workflow
2. Tests are executed against newly built binary artifact
3. Test suite's are easy to follow and can serve as example
4. Noir code and test code is separated
5. Failure of tests are sending to notification to Author (and/or team)

Note. Review an example test [6_array.test.js](https://github.com/noir-lang/build-nargo/blob/master/test/6_array.test.js)

**Comment by Savio-Sou** [comment]
@kobyhallx is this still relevant? (The Issue was transferred from the old Noir Tooling board.)

**Comment by kobyhallx** [comment]
This can be closed now as we introduced bunch of unit leve as well as e2e/integration tests.
